### PR TITLE
Add the user key to the set of tests in the test.yaml file

### PR DESCRIPTION
**Pull request by jafraustro**
## Description
Update tests.yaml files with `user: root`
## Changes Made
The command `groupadd -g 109 render` creates a new group called render with the Group ID 109.  Some tests failed because the RENDER group set inside the container (109) mismatches with the RENDER group of the runner. As workaround, some test need to be run as `root user`

### CODE REVIEW

**Review by tylertitsworth — CHANGES_REQUESTED** [review]
@jafraustro it seems that we are missing the group ID change from your last PR. Is that on purpose?

Please update your branch also.

**Comment by jafraustro** [comment]
> @jafraustro it seems that we are missing the group ID change from your last PR. Is that on purpose?
> 
> Please update your branch also.

**Comment by jafraustro** [comment]
> @jafraustro it seems that we are missing the group ID change from your last PR. Is that on purpose?
> 
> Please update your branch also.

Thanks Tyler, GID variable is added

**Review by tylertitsworth — APPROVED** [review]

**Review by tylertitsworth — APPROVED** [review]

**Comment by jitendra42** [comment]
due to memory issue integration tests are failing Jaime validated it locally

**Pull request merged**
